### ISSUE TITLE
[php8] Fatal error

### ISSUE THREAD

**Issue by Pross** [wp-seopress/wp-seopress-public#31]
Just updated to version 5.0 and get fatal error on all pages

```
[29-Jul-2021 16:00:13 UTC] PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /Users/pross/Sites/bb-test/wp-content/plugins/wp-seopress/src/Services/EnqueueModuleMetabox.php:38
Stack trace:
#0 /Users/pross/Sites/bb-test/wp-content/plugins/wp-seopress/src/Services/EnqueueModuleMetabox.php(38): method_exists(NULL, 'is_block_editor')
#1 /Users/pross/Sites/bb-test/wp-content/plugins/wp-seopress/src/Actions/Admin/ModuleMetabox.php(37): SEOPress\Services\EnqueueModuleMetabox->canEnqueue()
#2 /Users/pross/Sites/bb-test/wp-content/plugins/wp-seopress/src/Actions/Admin/ModuleMetabox.php(114): SEOPress\Actions\Admin\ModuleMetabox->enqueueModule(Array)
#3 /Users/pross/Sites/bb-test/wp-includes/class-wp-hook.php(303): SEOPress\Actions\Admin\ModuleMetabox->enqueueFrontend('')
#4 /Users/pross/Sites/bb-test/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /Users/pross/Sites/bb-test/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /Users/pross/Sites/bb-test/wp-includes/script-loader.php(2083): do_action('wp_enqueue_scri...')
#7 /Users/pross/Sites/bb-test/wp-includes/class-wp-hook.php(303): wp_enqueue_scripts('')
#8 /Users/pross/Sites/bb-test/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#9 /Users/pross/Sites/bb-test/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#10 /Users/pross/Sites/bb-test/wp-includes/general-template.php(3015): do_action('wp_head')
#11 /Users/pross/Repos/bb-theme/header.php(11): wp_head()
#12 /Users/pross/Sites/bb-test/wp-includes/template.php(770): require_once('/Users/pross/Re...')
#13 /Users/pross/Sites/bb-test/wp-includes/template.php(716): load_template('/Users/pross/Si...', true, Array)
#14 /Users/pross/Sites/bb-test/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#15 /Users/pross/Repos/bb-theme/page.php(1): get_header()
#16 /Users/pross/Sites/bb-test/wp-includes/template-loader.php(106): include('/Users/pross/Re...')
#17 /Users/pross/Sites/bb-test/wp-blog-header.php(19): require_once('/Users/pross/Si...')
#18 /Users/pross/Sites/bb-test/index.php(17): require('/Users/pross/Si...')
#19 {main}
  thrown in /Users/pross/Sites/bb-test/wp-content/plugins/wp-seopress/src/Services/EnqueueModuleMetabox.php on line 38
```

**Comment by Pross** [comment]
Here is a patch: 

```
diff --git a/src/Actions/Admin/ModuleMetabox.php b/src/Actions/Admin/ModuleMetabox.php
index 26ff019..63dd369 100644
--- a/src/Actions/Admin/ModuleMetabox.php
+++ b/src/Actions/Admin/ModuleMetabox.php
@@ -41,7 +41,7 @@ class ModuleMetabox implements ExecuteHooks
         $isGutenberg = false;
         if(function_exists('get_current_screen')){
             $currentScreen = get_current_screen();
-            if(method_exists($currentScreen,'is_block_editor')){
+            if( $currentScreen && method_exists($currentScreen,'is_block_editor')){
                 $isGutenberg = true === get_current_screen()->is_block_editor();

             }
diff --git a/src/Services/EnqueueModuleMetabox.php b/src/Services/EnqueueModuleMetabox.php
index b870a2c..cf71204 100644
--- a/src/Services/EnqueueModuleMetabox.php
+++ b/src/Services/EnqueueModuleMetabox.php
@@ -35,11 +35,11 @@ class EnqueueModuleMetabox
         if (function_exists('get_current_screen')) {
             $currentScreen = \get_current_screen();

-            if(method_exists($currentScreen, 'is_block_editor') &&  $currentScreen->is_block_editor() === false){
+            if( $currentScreen && method_exists($currentScreen, 'is_block_editor') &&  $currentScreen->is_block_editor() === false){
                 $response = false;
             }

-            if(!seopress_get_service('AdvancedOption')->getAccessUniversalMetaboxGutenberg() && method_exists($currentScreen, 'is_block_editor') &&  $currentScreen->is_block_editor() !== false){
+            if(!seopress_get_service('AdvancedOption')->getAccessUniversalMetaboxGutenberg() && $currentScreen && method_exists($currentScreen, 'is_block_editor') &&  $currentScreen->is_block_editor() !== false){
                 $response = false;
             }
         }
```

**Comment by wp-seopress** [comment]
Hi,

thank you, we'll check this ASAP!

**Comment by wp-seopress** [comment]
I confirm to you that a fix is coming soon in version 5.0.2.

ETA: today
