### ISSUE TITLE
Modules that slow down WP installation and breaks WP Cli profiling

### ISSUE THREAD

**Issue by rafaellop** [wp-seopress/wp-seopress-public#34]
The file `/src/Actions/Front/Schemas/PrintHeadJsonSchema.php` adds about 0.22s (which is a lot) to the processing time when profiling an URL using the WP CLI. In particular this code:

```
$jsons = seopress_get_service('JsonSchemaGenerator')->getJsonsEncoded(['organization',]);
```

Also the file `inc/functions/options-socia.php` causes critical error when testing with WP CLI in the line 358. Error: 

```
PHP Fatal error:  Uncaught Error: Call to undefined method PLL_Admin_Links::get_translation_url() 
in /wp-content/plugins/wp-seopress/inc/functions/options-social.php:358
Stack trace:
#0 /wp-includes/class-wp-hook.php(303): seopress_social_facebook_og_locale_hook('')
#1 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#2 /wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /wp-includes/general-template.php(3015): do_action('wp_head')
#4 /wp-content/themes/theme/header.php(36): wp_head()
#5 /wp-includes/template.php(770): require_once('/home/klient.dh...')
#6 /wp-content/plugins/wp-seopress/inc/functions/options-social.php on line 358
```
 
Code responsible:

```
foreach (PLL()->model->get_languages_list() as $language) {
  if (PLL()->curlang->slug !== $language->slug && PLL()->links->get_translation_url($language) && isset($language->facebook)) {
    $alternates[] = $language->facebook;
  }
}
```

**Comment by wp-seopress** [comment]
Hi @rafaellop 

thank you for this feedback.

Can you send us an email to contact@seopress.org please? so we can provide you a beta version that should improve this (if you want, no obligation). Thanks!
